### ISSUE TITLE
400 Bad Request when signing up

### ISSUE THREAD

**Issue by simlay** [chmoder/criterion.dev#4]
Hi there, found this project from twitter. Looks pretty cool!

Anyway, I went to signup and I keep getting a 400 Bad Request when going through the signup flow. I tried a couple different password types but had no success.

**Comment by chmoder** [comment]
Thanks for opening this issue @simlay, I resolved the error a few days ago and didn't notice this issue.  Sorry for the delay here, it was a small mistake on my part and apologize for the inconvenience.
