### ISSUE TITLE
Question: what is the size limit for uploading benchmarks?

### ISSUE THREAD

**Issue by jszwedko** [chmoder/criterion.dev#5]
I assume there is an intentional limit, but we got a 413 when trying to use criterion.dev with https://github.com/timberio/vector:

https://github.com/timberio/vector/runs/1658874288?check_suite_focus=true#step:17:3430

I was a bit surprised to see it uploading the SVGs and other generated assets from criterion-rs. Is this intentional? Looking at criterion.dev I would have assumed it'd be primarily driven off of the `raw.csv` files.

**Comment by chmoder** [comment]
Good question!  We added a feature that uploads the reports as well so that you can also see that data at any point in time if for example someone wants to narrow down a past performance regression.

Thanks for this report!  I will look into it and get back to you soon.

**Comment by chmoder** [comment]
It turns out this was an nginx default setting.  

`client_max_body_size` defaults to 1MB; we changed it to 8MB because some projects like this one have more information associated with them.

https://twitter.com/chmoder/status/1343573418101379074?s=20 shows how to view the uploaded report.
