### ISSUE TITLE
Expired certificate

### ISSUE THREAD

**Issue by calebcartwright** [chmoder/criterion.dev#7]
Seems the certificate on https://api.criterion.dev/ has expired, which is causing some test failure issues for us over on Shields.io

Any plans to renew/replace the cert?

```
$ curl -I https://api.criterion.dev/v1/chmoder/not-a-repo/status
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

![image](https://user-images.githubusercontent.com/13042488/136705395-f7bd1952-c0a0-49b9-883c-bdea5d4e45f4.png)

**Comment by PyvesB** [comment]
Seems like the certificate has since been renewed. 😉

**Comment by PyvesB** [comment]
Seems like the certificate has expired again on 03/02/2022. 😕

**Comment by calebcartwright** [comment]
@chmoder - not sure how the certificate expired again in such a relatively short time frame, but anything you can share around getting the issue resolved?

**Comment by chmoder** [comment]
I don't know how I missed this question, sorry for the delay.  I reinstalled certbot using snap instead of apt to resolve the SSL cert issue.  Thank you!
